### ISSUE TITLE
Fails on rpi2

### ISSUE THREAD

**Issue by BartAgterbosch** [filippobuletto/osmcwireguard#5]
Followed all steps on latest osmc, except installed gnupg2 prior since it was a requirement.
However, `sudo tar -xvf rbp2-source-'uname -r'.tar.bz2 rbp2-source-\'uname -r'/include/linux` fails for me stating it doesn't exist:
`tar: rbp2-source-5.10.78-2-osmc.tar.bz2: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now`

which probably results in the headers not getting installed:
`Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
Skipped.
Module build for kernel user.txt was skipped since the
kernel headers for this kernel does not seem to be installed.`

Am I doing something stupid here perhaps?

**Comment by filippobuletto** [comment]
Is the step
```bash
sudo apt-get install rbp2-headers-$(uname -r) rbp2-source-$(uname -r) ...
```
working?

**Comment by BartAgterbosch** [comment]
Sorry I just ditched osmc in favor of libreelec yesterday, as connman works, so I cannot currently check.
But I distinctly remember that that step did work, everything worked without fail up til unpacking rbp2-source-5.10.78-2-osmc.tar.bz2 as there was no such file (or newer version)

**Comment by filippobuletto** [comment]
No problem, this guide is a no-brainer / best-effort and I cannot full support every problem that is encountered.

Thanks for your inquiry nonetheless!
